### ISSUE TITLE
HTML input labels

### ISSUE THREAD

**Issue by bobbysebolao** [FACN7/MOK_Rental#24]
To link an HTML label with an input field, the ```for``` attribute must match the ```id``` of the ```<input>``` element. e.g.

```    
<form>
      <label for="lfname">First name:</label> 
      <input id="lfname" name="fname" type="text" />
    </form>
```

There are a few label ```for``` attributes that you should change in your index.html and rentCar.html. This will mean that screen readers will hear the correct label text read out loud when they focus on an input field!

**Comment by MohamadD** [comment]
done!
