### ISSUE TITLE
Sanitising db inputs in SQL

### ISSUE THREAD

**Issue by bobbysebolao** [FACN7/MOK_Rental#25]
At the moment, users can submit any characters they like (letters, numbers, special characters) to the users table in your db. 

It would be worth experimenting with different data types in your build script

```
  CREATE TABLE
  IF NOT EXISTS users
  (
  user_id SERIAL PRIMARY KEY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  city TEXT NOT NULL,
  phone TEXT NOT NULL
);
```

e.g. the ```VARCHAR``` character type might be a better choice for first name and last name fields, because you can specify a character limit (unlike ```TEXT```, which has no limit).

Look into what value type you could use instead of ```TEXT``` for the phone number field.

**Comment by MohamadD** [comment]
thank U .. i think its done !
